fix(chip): spacing & slots
scania-digital-design-system/tegel pull request #213
Opened 2023-07-12 14:10 UTC by theJohnnyMe

**Describe pull-request**  
Fixing issues with padding and slots in the Chip component.

**Solving issue**  
Fixes: [DTS-2074](https://tegel.atlassian.net/browse/DTS-2074)

**How to test**  
1. Go to Netlify preview link
2. Check that component has all slots mentioned under Notes tab
3. Check that component padding is correct for all states of component: large, small, without icons, with prefix, with suffix...

**Suggested test steps**
- [ ] Browser testing (Chrome, Safari, Firefox) 
- [ ] Keyboard operability
- [ ] Interactive elements have labels.
- [ ] Storybook controls
- [ ] Design/controls/props is aligned with other components 
- [ ] Dark/light mode and variants 
- [ ] Input fields – values should be displayed properly 
- [ ] Events

**Additional context**  
I had to introduce slots for prefixes and suffixes in order to assign correct padding to the label as it changes if icons are present or not. 

[DTS-2074]: https://tegel.atlassian.net/browse/DTS-2074?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-07-12 15:19 UTC, alexandereneroth requested changes
Nice! 🙌

I found 1 issue and 1 potential issue to check before approval:
- Need to fix the the radio/checkbox types in storybook as well
<img width="309" alt="Screenshot 2023-07-12 at 17 19 28" src="https://github.com/scania-digital-design-system/tegel/assets/8556022/e9e304da-29d2-4cb4-808d-fa4525462928">

- The star icon is not centered, I wonder if this is a problem with the star icon or the chip component?
👇 
<img width="43" alt="Screenshot 2023-07-12 at 17 09 36" src="https://github.com/scania-digital-design-system/tegel/assets/8556022/c6f26965-05e5-4b6e-bb94-f9ad66236c73">

2023-07-13 07:04 UTC, theJohnnyMe commented
> Nice! 🙌
> 
> I found 1 issue and 1 potential issue to check before approval:
> 
> * Need to fix the the radio/checkbox types in storybook as well
> 
> <img alt="Screenshot 2023-07-12 at 17 19 28" width="309" src="https://user-images.githubusercontent.com/8556022/253019933-e9e304da-29d2-4cb4-808d-fa4525462928.png">
> * The star icon is not centered, I wonder if this is a problem with the star icon or the chip component?
>   👇
> 
> <img alt="Screenshot 2023-07-12 at 17 09 36" width="43" src="https://user-images.githubusercontent.com/8556022/253018777-c6f26965-05e5-4b6e-bb94-f9ad66236c73.png">

Nice finding Alex, I think I just forgot to update story files of Checkbox and Radio button type, on it now ;)

2023-07-13 07:35 UTC, nathalielindqvist commented on core/src/components/chip/chip.tsx
> + * @slot suffix- Slot for the suffix icon.
```suggestion
 * @slot suffix - Slot for the suffix icon.
```

2023-07-13 07:35 UTC, nathalielindqvist commented on core/src/components/chip/chip.tsx
> + * @slot suffix- Slot for the suffix icon.
Missing space before the dash lead to the slot docs not being rendered properly in the readme

2023-07-13 07:37 UTC, nathalielindqvist submitted a review, later dismissed
Great work! Just a small comment on the slot docs, otherwise looks good to me 🔥

2023-07-13 08:14 UTC, nathalielindqvist approved these changes

2023-07-13 08:25 UTC, alexandereneroth approved these changes
💯

2023-07-13 08:34 UTC, merged