fix(table): scroll instead of expanding parent
scania-digital-design-system/tegel pull request #721
Opened 2024-08-15 11:37 UTC by mistermalm

## **Describe pull-request**  
Any elements, that are wider than the available width inside the expand-row slot, should overflow instead of expanding the entire table.

## **Issue Linking:**  
_Choose one of the following options_
- **Jira:** [CDEP-3353: The expand-row slot expands the entire table instead of overflowing](https://tegel.atlassian.net/browse/CDEP-3353)     

## **How to test**  
_Provide detailed steps for testing, including any necessary setup._
1. Go to: `table-component-expandable-rows.stories.tsx`
2. Replace `<div slot="expand-row">Hello world 1</div>` with some wider content for example:  
```
<div slot="expand-row">
  <tds-body-cell cell-value="Test value 1" cell-key="truck"></tds-body-cell>
  <tds-body-cell cell-value="Test value 2" cell-key="driver"></tds-body-cell>
  <tds-body-cell cell-value="Test value 3" cell-key="country"></tds-body-cell>
  <tds-body-cell cell-value="Test value 4" cell-key="mileage"></tds-body-cell>
  <tds-body-cell cell-value="Test value 1" cell-key="truck"></tds-body-cell>
</div>
```
3. Go to the storybook Table -> Expandable Rows
4. Expand the row you edited and see that it's now scrollable instead of expanding the whole table.

## **Additional context**  
Does anyone have a suggestion for the same behaviour using other CSS properties? The max-width: 1px is working but it's not super clear what it does for anyone who just looking briefly at the styling.

2024-08-19 07:06 UTC, Lunkan89 commented
I think we should just check in with a designer on this one as well.

2024-08-22 12:10 UTC, theJohnnyMe requested changes
Fix does work in Chrome and Safari, but not in Firefox:

<img width="1249" alt="Screenshot 2024-08-22 at 14 08 44" src="https://github.com/user-attachments/assets/99410745-c34f-4aa3-a6e7-ef6b5875c095">

I will think if I can come up with some CSS trick or we might need to use JS for it.

2024-08-26 07:17 UTC, theJohnnyMe commented
As it seems, what we propose here should not endanger any current implementation of an expanded row. It seems to work good in Firefox, Chrome and Safari, therefore I approve it.

NIce work @mistermalm ;)

2024-08-26 07:17 UTC, theJohnnyMe approved these changes

2024-08-26 07:39 UTC, timrombergjakobsson approved these changes

2024-08-26 07:40 UTC, Lunkan89 approved these changes

2024-08-26 10:41 UTC, merged